version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1-master
          paths:
            - /caches/image.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Test
          command: ./test.sh
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/image.tar app $(docker history -q app | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/image.tar
